default_settings: null
behaviors:
  DReCon-Modular:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.009
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 5000000
    max_steps: 128000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: true
    self_play: null
    behavioral_cloning: null
    framework: pytorch
env_settings:
  env_args:
  - --spawn-env=DReConLSPD
  - --num-spawn-envs=20
  base_port: 5005
  num_envs: 15 #1
engine_settings:
  no_graphics: true
debug: false
