behaviors:
  default:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      beta: 5.0e-3
      buffer_size: 10240
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      num_epoch: 3
    network_settings:
      normalize: false
      num_layers: 2
      hidden_units: 128
      vis_encode_type: simple
      # memory:
      #     memory_size: 256
      #     sequence_length: 64
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5.0e4
    time_horizon: 64
    threaded: true
    summary_freq: 1000

  MarathonManSlash-v0:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 16
      beta: .00001
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 1e-4
      batch_size: 4096
      buffer_size: 114688 # 768 * 28
    time_horizon: 100
    summary_freq: 100000
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 512
    max_steps: 128e6
    threaded: true
